import './ResultPanel.css'

function duration(value) { if (!value) return ''; const minutes = Math.floor(value / 60); const seconds = String(Math.floor(value % 60)).padStart(2, '0'); return `${minutes}:${seconds}` }

export default function ResultPanel({ videoMeta, loading, progress, resultUrl, onDownloadFormat, onReset }) {
  return <div className="result-panel">
    <div className="video-head"><div className="video-thumb-wrap">{videoMeta.thumbnail ? <img src={videoMeta.thumbnail} alt="" className="video-thumb" /> : <span className="material-icons-round">smart_display</span>}</div><div className="video-details"><span className="label-sm">Ready to download</span><h2 className="video-title">{videoMeta.title}</h2><p className="video-meta">{videoMeta.channel || 'YouTube'} {videoMeta.duration ? ` · ${duration(videoMeta.duration)}` : ''}</p></div></div>
    {loading ? <div className="download-state"><span className="spinner" /><p>Preparing your download…</p><div className="progress-track"><div className="progress-fill" style={{ width: `${progress}%` }} /></div><span className="progress-percent">{Math.round(progress)}%</span></div> : resultUrl ? <div className="download-success"><span className="material-icons-round">check_circle</span><h3>Your file is ready</h3><p>Download it now; temporary files are cleaned up automatically.</p><a className="btn-primary" href={resultUrl} download><span className="material-icons-round">download</span>Download file</a></div> : <div className="format-area"><div className="format-heading"><div><p className="label-sm">Download as</p><h3>Choose a quality</h3></div><span className="format-tip">MP4 &amp; M4A</span></div><div className="format-grid">{videoMeta.formats.map((format) => <button className={`format-btn ${format.id === 'best' ? 'featured' : ''}`} key={format.id} onClick={() => onDownloadFormat(format.id)} type="button"><span className="format-icon material-icons-round">{format.id === 'audio' ? 'headphones' : 'movie'}</span><span><strong>{format.label}</strong><small>{format.detail}</small></span><span className="material-icons-round arrow">arrow_forward</span></button>)}</div></div>}
    <div className="result-footer"><button className="btn-ghost" onClick={onReset} type="button"><span className="material-icons-round">arrow_back</span>Choose another video</button></div>
  </div>
}
